### ISSUE TITLE
Create tokenizer with offsets support for BERT (or similar) embeddings

### ISSUE THREAD

**Issue by frreiss** [frreiss/text-extensions-for-pandas#4]
To implement part 3 of the CoNLL demo, we need to convert each document in the CoNLL-2003 corpus into a dataframe with 3 columns:
```
<span of token> | <label of token> | <embedding of token>
```
Once we have such a dataframe, we can quickly train up multiple models on the prebuilt embeddings and use those models to zero in on incorrectly-labeled entities in the data set.

To create this dataframe, we need to retokenize the corpus using the tokenizer that the BERT embeddings are designed for. That tokenizer's code can be found [here](https://github.com/tensorflow/models/blob/master/official/nlp/bert/tokenization.py).

Unfortunately, the BERT tokenizer does **not** output the character (or code point) offsets of the tokens that it produces. To use this tokenizer, we need to modify the implementation in `tokenization.py` so that it produces begin and end offsets for every token.I recommend that we contribute this functionality back to the [official BERT models](https://github.com/tensorflow/models) as a pull request, so that we don't need to worry about our changes getting stomped on in the future.

**Potential alternate approach:** Look through the changes and comments of `https://github.com/huggingface/transformers/pull/2674` to figure out how to enable huggingface's implementation of tokenization for BERT embeddings that captures character offsets, assuming such an implementation exists.

**Comment by BryanCutler** [comment]
@frreiss looks like huggingface transformers can return offsets for tokenizers if based on Rust, not just Python. For BERT, they have `FastBertTokenizer` that seems like what we want:

```python
In [16]: from transformers import BertTokenizerFast                                                                          

In [17]: tokenizer = BertTokenizerFast.from_pretrained('bert-base-uncased')                                                  

In [18]: tokenized_text = tokenizer.encode_plus(text, return_offsets_mapping=True)                                           

In [19]: tokenized_text                                                                                                      
Out[19]: 
{'input_ids': [101,
  101,
  2040,
  2001,
  3958,
  27227,
  1029,
  102,
  3958,
  27227,
  2001,
  1037,
  13997,
  11510,
  102,
  102],
 'token_type_ids': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
 'offset_mapping': [None,
  (0, 5),
  (6, 9),
  (10, 13),
  (14, 17),
  (18, 24),
  (25, 26),
  (26, 31),
  (32, 35),
  (36, 42),
  (43, 46),
  (47, 48),
  (49, 55),
  (55, 58),
  (58, 63),
  None]}

In [20]: text                                                                                                                
Out[20]: '[CLS] Who was Jim Henson ? [SEP] Jim Henson was a puppeteer [SEP]'

In [21]: text[:5]                                                                                                            
Out[21]: '[CLS]'

In [22]: text[6:9]                                                                                                           
Out[22]: 'Who
```

**Comment by frreiss** [comment]
Great to hear! So it looks like we are unblocked for the next step. Let me close out this issue and open a separate one to track part 3 of the CoNLL demo more broadly.
